# Site settings
title: Tobi's Cublog
email: tobias.peter@bluewin.ch
description: > # this means to ignore newlines until "baseurl:"
  In this little blog I'll write about cubing stuff, keep hold of my progress and try to entertain you with this tiny textgems.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "tobip.ch/cublog" # the base hostname & protocol for your site
github_username:  tobipch

# Build settings
markdown: kramdown
